### ISSUE TITLE
Travis-CI dislikes APT addon

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/sox-server#4]
Build passes locally.

Travis seems to dislike...
```yml
sudo: true
before_install:
  - sudo apt-get install sox
```
...so I tried...
```yml
addons:
  apt:
    packages:
    - sox
```
...but that's broken too.

See also:
- https://github.com/travis-ci/travis-yaml/issues/58
- https://github.com/travis-ci/travis-yaml/issues/68
